# Generated by Django 5.2.8 on 2025-11-11 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, help_text='Prevents creating more than one settings row.', unique=True)),
                ('site_title', models.CharField(default='EduStage Academy', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('base_url', models.URLField(blank=True, help_text='e.g. https://myschool.edu.np')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('default_language', models.CharField(default='en', max_length=40)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=60)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=32)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('favicon', models.ImageField(blank=True, help_text='Upload .ico or .png', upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png'])])),
                ('logo_light', models.ImageField(blank=True, upload_to='branding/')),
                ('logo_dark', models.ImageField(blank=True, upload_to='branding/')),
                ('logo_mobile', models.ImageField(blank=True, upload_to='branding/')),
                ('app_icon_pwa', models.ImageField(blank=True, help_text='512x512 PNG recommended for PWA', upload_to='branding/')),
                ('theme_primary_color', models.CharField(default='#004aad', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #004aad', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('font_family', models.CharField(default='Rubik', max_length=80)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('homepage_title_meta', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated (optional)', max_length=250)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('analytics_id', models.CharField(blank=True, help_text='GA4 / GTM / etc.', max_length=40)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('error_reporting_enabled', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('version_info', models.CharField(blank=True, help_text='Read-only or filled by releases.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
