# Generated by Django 5.2.8 on 2025-11-11 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload .ico or .png', upload_to='static/branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png'])]),
        ),
    ]
