# Generated by Django 5.2.8 on 2025-11-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, upload_to='static/branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_light',
            field=models.ImageField(blank=True, upload_to='static/branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_mobile',
            field=models.ImageField(blank=True, upload_to='static/branding/'),
        ),
    ]
