# Generated by Django 5.2.8 on 2025-11-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
