# Generated by Django 5.2.8 on 2025-11-11 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject_taught', models.CharField(help_text='e.g., Mathematics, Science, English', max_length=120)),
                ('photo', models.ImageField(blank=True, upload_to='staff/photos/')),
                ('short_bio', models.TextField(blank=True, help_text='A short introduction or biography.', max_length=400)),
                ('facebook', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('instagram', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the website.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Teachers/Staffs',
                'verbose_name_plural': 'Teacher/Staff',
                'ordering': ['order', 'name'],
            },
        ),
    ]
