# Generated by Django 5.2.8 on 2025-11-11 07:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, unique=True)),
                ('hero_title', models.CharField(default='Welcome to Our School', max_length=160)),
                ('hero_subtitle', models.CharField(blank=True, default='Learn • Grow • Achieve', max_length=220)),
                ('hero_background', models.ImageField(blank=True, upload_to='static/homepage/hero/')),
                ('hero_cta_text', models.CharField(blank=True, default='Get Started', max_length=40)),
                ('hero_cta_url', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('show_features', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('show_leadership', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('show_partners', models.BooleanField(default=True)),
                ('show_events', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='static/homepage/og/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='static/homepage/hero/slides/')),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('subheadline', models.CharField(blank=True, max_length=220)),
                ('cta_text', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='homepage.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon_class', models.CharField(blank=True, help_text="e.g. 'fa fa-graduation-cap' or 'ti-light-bulb'", max_length=64)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='homepage.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('date_text', models.CharField(blank=True, help_text='e.g., 12 Dec, 3:00 PM', max_length=60)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('link', models.URLField(blank=True)),
                ('banner', models.ImageField(blank=True, upload_to='static/homepage/events/')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='homepage.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=160)),
                ('url', models.URLField(blank=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('homepage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Announcement Bar',
                'verbose_name_plural': 'Announcement Bar',
            },
        ),
        migrations.CreateModel(
            name='LeadershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('chairperson', 'Chairperson'), ('director', 'Director')], default='principal', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('title_line', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='static/homepage/leadership/')),
                ('message', models.TextField(blank=True)),
                ('profile_link', models.URLField(blank=True)),
                ('align', models.CharField(choices=[('left', 'Image Left'), ('right', 'Image Right')], default='right', max_length=10)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_messages', to='homepage.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='static/homepage/partners/')),
                ('url', models.URLField(blank=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='homepage.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(help_text='Number or short text (e.g., 1.2K)', max_length=32)),
                ('suffix', models.CharField(blank=True, help_text='Optional suffix like %, +, yrs', max_length=12)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='homepage.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(blank=True, upload_to='static/homepage/testimonials/')),
                ('quote', models.TextField()),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='homepage.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
